# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: test.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    2,
    '',
    'test.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntest.proto\x12\tmypackage\"\xd7\x01\n\x06Person\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\x05\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12-\n\x06phones\x18\x04 \x03(\x0b\x32\x1d.mypackage.Person.PhoneNumber\x1aH\n\x0bPhoneNumber\x12\x0e\n\x06number\x18\x01 \x01(\t\x12)\n\x04type\x18\x02 \x01(\x0e\x32\x1b.mypackage.Person.PhoneType\"+\n\tPhoneType\x12\n\n\x06MOBILE\x10\x00\x12\x08\n\x04HOME\x10\x01\x12\x08\n\x04WORK\x10\x02\"\x1c\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1d\n\nHelloReply\x12\x0f\n\x07message\x18\x01 \x01(\t2E\n\x07Greeter\x12:\n\x08SayHello\x12\x17.mypackage.HelloRequest\x1a\x15.mypackage.HelloReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'test_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PERSON']._serialized_start=26
  _globals['_PERSON']._serialized_end=241
  _globals['_PERSON_PHONENUMBER']._serialized_start=124
  _globals['_PERSON_PHONENUMBER']._serialized_end=196
  _globals['_PERSON_PHONETYPE']._serialized_start=198
  _globals['_PERSON_PHONETYPE']._serialized_end=241
  _globals['_HELLOREQUEST']._serialized_start=243
  _globals['_HELLOREQUEST']._serialized_end=271
  _globals['_HELLOREPLY']._serialized_start=273
  _globals['_HELLOREPLY']._serialized_end=302
  _globals['_GREETER']._serialized_start=304
  _globals['_GREETER']._serialized_end=373
# @@protoc_insertion_point(module_scope)
